// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  education: dynamic(() => import("./Education")),
  experience: dynamic(() => import("./Experience")),
  footer: dynamic(() => import("./Footer")),
  header: dynamic(() => import("./Header")),
  hobbies: dynamic(() => import("./Hobbies")),
  introduction: dynamic(() => import("./Introduction")),
  rich_text: dynamic(() => import("./RichText")),
};
